# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-30 15:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=160)),
                ('title', models.CharField(max_length=80)),
                ('language', models.CharField(max_length=80)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='BookPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_date', models.DateField(default=datetime.datetime(2018, 10, 30, 15, 41, 41, 69000, tzinfo=utc))),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keetab_app.Book')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('age', models.IntegerField()),
                ('number', models.IntegerField()),
                ('city', models.CharField(max_length=80)),
                ('admin', models.BooleanField(default=False)),
                ('balance', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='bookpurchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keetab_app.User'),
        ),
    ]
