# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-03 02:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('keetab_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookpurchase',
            options={'ordering': ['-purchased_date']},
        ),
        migrations.AlterField(
            model_name='bookpurchase',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boughtbooks', to='keetab_app.Book'),
        ),
        migrations.AlterField(
            model_name='bookpurchase',
            name='purchased_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 3, 2, 24, 9, 479000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bookpurchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boughtbooks', to='keetab_app.User'),
        ),
    ]
